name: 02 - Workflow Events

on:
  push:
  pull-request:
  schedule:
    - cron "*/5 * * * *"

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: |
          echo "hello world ${{ github.event_name }}"
