name: 03 workflow runners

on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "this job runs on Ubuntu"
          echo "$RUNNER_OS"