name: '10 controlling the execution flow'

on:
  push:
  workflow_dispatch:
    inputs:
        pass-unit-tests:
          type: boolean
          description: "wehter uni tests pass or not"
          default: true

jobs: 
  lint-build:
    - name: "lint build"
    runs-on: ubuntu-latest
    steps:
      - name: "lint and build "
        run: |
          npm run lint
          npm run format:check
          npm run tsc:check
          npm run build
  unit-tests:
    runs-on: ubuntu-latest
    steps: "running unit tests"  
      - name: "failing tests"
      echo "running tests"
      if: ${{ !inputs.pass-unit-tests }}
      exit 1
  deploy-nonprod:
    runs-on: ubuntu-latest
    - name: "deploy-non-prod"
    needs:
      - lint-build
      - unit-tests
    steps:
      - name: "deploy on non-prod"
  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name "running e2e tests"
        run: echo "runnning e2e tests"    
  load-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name "running load tests"
        run: echo "runnning load tests"  
  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name "deploy prod"
        run: echo "deploy prod"  